language: python

sudo: false

python:
    - "2.7"
    - "3.4"
    - "3.5"

before_install:
    - mkdir ~/Desktop
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - pwd
    - export PATH=/home/travis/miniconda2/bin:$PATH
    - export PYTHONPATH=/home/travis/cuthbertLab/music21base
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - echo next line commented out temporarily because of problems with conda and numpy/enum34...
    - echo conda update --yes conda
    - wget -q http://download.linuxaudio.org/lilypond/binaries/linux-64/lilypond-2.19.15-1.linux-64.sh
    - pip install coveralls
    - sh lilypond-2.19.15-1.linux-64.sh --batch
    - export PATH=/home/travis/bin:$PATH

install:
    - conda install --yes python=$TRAVIS_PYTHON_VERSION pyqt
    - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy 
    - conda install --yes python=$TRAVIS_PYTHON_VERSION scipy 
    - conda install --yes python=$TRAVIS_PYTHON_VERSION matplotlib 
    - conda install --yes python=$TRAVIS_PYTHON_VERSION setuptools 
    - conda install --yes python=$TRAVIS_PYTHON_VERSION coverage
    - cd ..
    - mv music21 music21base
    - cd music21base
    - python -m compileall music21

script:
    - python -c 'from music21.test.testSingleCoreAll import travisMain as tm; tm()'
    
after_success:
      coveralls