language: python

matrix:
    include:
        - python: 3.6
          dist: xenial
          sudo: false
        - python: 3.7
          dist: xenial
          sudo: true
        - python: 3.8
          dist: xenial
          sudo: true

services:
  - xvfb

before_install:
    # needed for some tests that add Desktop
    - mkdir ~/Desktop
    - sudo apt-get install -y libpng-dev
    - sudo apt-get install -y python-qt4
    - export PYTHONPATH=/home/travis/cuthbertLab/music21base
    - wget -q http://lilypond.org/downloads/binaries/linux-64/lilypond-2.19.83-1.linux-64.sh
    - pip3 install coveralls
    - sh lilypond-2.19.83-1.linux-64.sh --batch
    - export PATH=/home/travis/bin:$PATH

install:
    - pip install -r requirements.txt
    - pip install scipy
    - pip install setuptools
    - pip install coverage
    - cd ..
    - mv music21 music21base
    - cd music21base
    - python -m compileall music21

script:
    - python -c 'from music21.test.testSingleCoreAll import travisMain as tm; tm()'

after_success:
    - if [ "$TRAVIS_PYTHON_VERSION" == "3.6" ]; then coveralls; fi
